@props(['title'])

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="robots" content="index,follow">

        <title>{{ config('app.name', 'Laravel') }} - {{ $title }}</title>

        <meta name="description" content="An artificial intelligence powered blog - A collection of posts randomly generated by artificial intelligence">

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-200 flex flex-col">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="py-6">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main class="mt-6 mb-6 flex-1 container mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
                <div class="fixed bottom-4 left-0 right-0 z-10" role="alert" x-data="{ show: true }" x-show="show" x-transition>
                    <div class="max-w-7xl mx-auto bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4 rounded shadow">
                        <p class="text-2xl font-bold mb-2 flex justify-between">Disclaimer <span class="text-4xl cursor-pointer" title="Close disclaimer" @click="show = false">&times;</span></p>
                        <p class="mb-2 text-sm">The texts and images in this blog are generated randomly by artificial intelligence and may not be accurate or reflect the opinion of the site owner. The information presented is purely for entertainment purposes and should not be considered as professional advice or factual.</p> 
                        <p class="mb-2 text-sm">The site owner holds no responsibility for any inaccuracies or misunderstandings that may arise from the use of this content. Readers are encouraged to verify any information presented and use their own judgment when interpreting the content of this blog.</p>
                        <p class="text-sm">If you want to read human created, and hopefully more interesting content, you can <a href="https://jycurien.fr" class="text-blue-600 hover:underline" target="_blank" rel="noopener">visit my website</a>.</p>
                    </div>
                </div>
                {{ $slot }}
            </main>

            <footer class="bg-white p-4">
                <p class="text-center">&copy; 2023 - Jean-Yves Curien</p>
            </footer>
        </div>
    </body>
</html>
